
using System;
using UnityEngine;
using UnityEngine.SceneManagement;
//유니티에서 싱글톤패턴 만들시 고려해야할 부분 
/*
    1. 싱글톤클래스가 닫히는 중일때 Thread 처럼 여러곳에서 동시다발적으로 접근하는경우 처리가 필요
    2. unity GameObject에 들어가야 씬에 올라갈수있기에 오브젝트 하나당 하나씩해서 중복생성에 관한 처리필요 
        2-1 . Awake 에서 생성될때 확인
        2-2 . 싱글톤클래스 호출시 확인
    3. 씬 변환 시 오브젝트가 초기화되니 초기화 안되게 DontDestroyOnLoad(instance.gameObject); 함수를 사용 
 
    4. 상속받은 클래스가 제네릭이면 AddComponent에서 자료의 형태를 찾을수가없다.
    - 유니티에서의 싱글톤은 나중에 생성된것을 사용하는것이 낫다.?
    - 게으른 할당?
 */
//T 는 반드시 컴퍼넌트 여야 한다
//where 는 조건 걸기위해 작성한다.
public class Singleton<T> : MonoBehaviour where T : Component
{
    
    /// <summary>
    /// 이미 종료처리에 들어갔는지 확인하기 위한 변수
    /// </summary>
    private static bool isShutDown = false;
    /// <summary>
    /// 싱글톤의 객체
    /// </summary>
    private static T instance;
    /// <summary>
    /// 싱글톤 객체를 읽기 위한 프로퍼티. 객체가 많들어지지 않았으면 새로만든다.
    /// </summary>
    public static T Instance
    {
        get
        {
            if (isShutDown) 
            {//종료처리중인지 확인
                Debug.LogWarning($"{typeof(T).Name}은 이미 삭제 중이다.");
                return null; //처리하지말라고 null을 넘긴다.
            }
            if (instance == null)
            {
                if (FindObjectOfType<T>() == null)
                { //씬에 싱글톤이있는지 확인
                    GameObject gameObj = new GameObject(); //오브젝트만들어서 
                    gameObj.name = $"{typeof(T).Name} Singleton"; //이름추가하고
                    instance = gameObj.AddComponent<T>(); //싱글톤객체에 추가하여 생성
                    DontDestroyOnLoad(instance.gameObject); //씬이 사라질때 게임오브젝트가 삭제되지 안하게하는 함수
                }
            }
            return instance;
        }
    }

    protected virtual void Awake()
    {
        if (instance == null)
        { //씬에 배치되어있는 첫번째 싱글톤  게임오브젝트
            instance = this as T;
            DontDestroyOnLoad(instance.gameObject); //씬이 사라질때 게임오브젝트가 삭제되지 안하게하는 함수
        }
        else
        { //첫번째 싱글톤 게임 오브젝트가 만들어진 이후에 만들어진 싱글톤 게임 오브젝트
            if (instance != this)
            { //두개만들어졌는데 같은거일수도있어서 아닐경우만 처리한다. 
                Destroy(this.gameObject);  //첫번째 싱글톤과 다른 객체이면 삭제
            }
        }
    }


    protected virtual void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }


    protected virtual void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        
    }
    /// <summary>
    /// 프로그램이 종료될때 실행되는 함수.
    /// </summary>
    private void OnApplicationQuit()
    {
        isShutDown = true; //종료 표시
    }

    protected virtual void OnSceneLoaded(Scene scean, LoadSceneMode mode)
    {
        Init(scean,mode);
    }
    protected virtual void Init(Scene scene , LoadSceneMode mode) { 
        
    }
}

